default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/cohnmanager_development

test:
  <<: *default
  database: db/cohnmanager_test

production:
  <<: *default
  database: db/cohnmanager
